// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zseecrekkomozzvblcka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZWVjcmVra29tb3p6dmJsY2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjExMDYsImV4cCI6MjA3Mjc5NzEwNn0.-rAzMCf9XIw_KnOLQ5uGbsDcSM6uSv3N1Cxyu8rhQrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});